function outputdecaystruct = checkDecayStruct(inputdecaystruct)
% use this function to make decay_struct generated by older version of GUI
% compatible with newer version.

load('FitResultTemplate.mat')

%field names
fnames = {'decay','name','filename','image','selected_pixel','setting',...
    'pathname','flimblock','time','decay_handle','fit','fit_handle','residual_handle',...
    'residual','fit_result','Chi_sq','fit_region','noise_region','fitting_method',...
    'laserT','irf','time_irf','irfname','irf_handle','refcurve','refcurvename',...
    'refcurve_handle','fit_detail','nexpo','fitvar'};

detailfields_LS = {'cvg_hst','dp'};
detailfields_Gibbs = {'dp','p_vec','post','Nsample','Nburn'};
detailfields_Grid = {'dp','marg_post','p_vec','post','prior'};


lackingfields = fnames(~isfield(inputdecaystruct,fnames));   %fields in 'fieldnames' not in inputdecaystruct. to be added
orgfnames = fieldnames(inputdecaystruct);%field names in inputdecaystruct
additionalfields = setdiff(orgfnames,fnames);  %fields in inputdecaystruct not in 'fieldnames'. to be removed.

%add lacking fields
for j = 1:length(lackingfields)
    inputdecaystruct = setfield(inputdecaystruct,lackingfields{j},[]);
end
if isempty(inputdecaystruct.fitting_method)
    inputdecaystruct.fitting_method = 0;
end
if isempty(inputdecaystruct.fit_result)
    inputdecaystruct.fit_result = FitResultTemplate;
end
if isempty(inputdecaystruct.fit_detail)
    inputdecaystruct.fit_detail = struct;
end

fitting_method = inputdecaystruct.fitting_method;
fit_detail = inputdecaystruct.fit_detail;
%remove additional fields, and transfer the important information to
%another fields
switch fitting_method
    case 1
        for j = 1:length(detailfields_LS)
            if ismember(detailfields_LS{j},additionalfields)
                fit_detail = setfield(fit_detail,detailfields_LS{j},getfield(inputdecaystruct,detailfields_LS{j}));
            elseif isfield(fit_detail,detailfields_LS{j})==0
                fit_detail = setfield(fit_detail,detailfields_LS{j},[]);
            end
        end
    case 2
        for j = 1:length(detailfields_Gibbs)
            if ismember(detailfields_Gibbs{j},additionalfields)
                fit_detail = setfield(fit_detail,detailfields_Gibbs{j},getfield(inputdecaystruct,detailfields_Gibbs{j}));
            elseif isfield(fit_detail,detailfields_Gibbs{j})==0
                fit_detail = setfield(fit_detail,detailfields_Gibbs{j},[]);
            end
        end
    case 3
        for j = 1:length(detailfields_Grid)
            if ismember(detailfields_Grid{j},additionalfields)
                fit_detail = setfield(fit_detail,detailfields_Grid{j},getfield(inputdecaystruct,detailfields_Grid{j}));
            elseif isfield(fit_detail,detailfields_Grid{j})==0
                fit_detail = setfield(fit_detail,detailfields_Grid{j},[]);
            end
        end
end
inputdecaystruct.fit_detail = fit_detail;
inputdecaystruct = rmfield(inputdecaystruct,additionalfields);

outputdecaystruct = orderfields(inputdecaystruct);

